language: node_js

node_js:
  - "7"

before_script:
  - npm install -g webpack babel
  - npm install

script:
  - npm run build
  - npm test

after_success:
  - npm run coverage

deploy:
  provider: npm
  email: "hamikhambardzumyan25@gmail.com"
  api_key: "21d0fa58-f2a7-4e6a-9db8-1bd653a2f5b2"
  on:
    branch: master
